repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.12
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v2.1.0
  hooks:
  - id: mypy
    name: Run MyPy typing checks.
    args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
